"""initial

Revision ID: 48ab096176f5
Revises: 
Create Date: 2026-05-20 12:24:05.728954
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '48ab096176f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intel_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severitylevel'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('channels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_table('isps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_competitor', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'monitoring_paused', name='ispstatus'), nullable=False),
    sa.Column('scraper_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_isps_is_competitor'), 'isps', ['is_competitor'], unique=False)
    op.create_index(op.f('ix_isps_slug'), 'isps', ['slug'], unique=True)
    op.create_table('weekly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_week', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipients', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_week')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_flat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bonus_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('free_months', sa.Integer(), nullable=True),
    sa.Column('applicable_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_is_active'), 'campaigns', ['is_active'], unique=False)
    op.create_index(op.f('ix_campaigns_isp_id'), 'campaigns', ['isp_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('plan_type', sa.Enum('residential', 'business', 'enterprise', 'fiber', 'wireless', name='plantype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'discontinued', 'promotional', 'coming_soon', name='planstatus'), nullable=False),
    sa.Column('download_mbps', sa.Integer(), nullable=False),
    sa.Column('upload_mbps', sa.Integer(), nullable=True),
    sa.Column('speed_raw', sa.String(length=50), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_quarterly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_annual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_raw', sa.String(length=50), nullable=True),
    sa.Column('setup_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_included', sa.Boolean(), nullable=False),
    sa.Column('fup_gb', sa.Integer(), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=False),
    sa.Column('contract_months', sa.Integer(), nullable=False),
    sa.Column('bundles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bundle_flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scrape_url', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isp_id', 'normalized_name', 'download_mbps', name='uq_plan')
    )
    op.create_index(op.f('ix_plans_download_mbps'), 'plans', ['download_mbps'], unique=False)
    op.create_index(op.f('ix_plans_isp_id'), 'plans', ['isp_id'], unique=False)
    op.create_index(op.f('ix_plans_plan_type'), 'plans', ['plan_type'], unique=False)
    op.create_index(op.f('ix_plans_price_monthly'), 'plans', ['price_monthly'], unique=False)
    op.create_index(op.f('ix_plans_status'), 'plans', ['status'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plans_found', sa.Integer(), nullable=False),
    sa.Column('plans_new', sa.Integer(), nullable=False),
    sa.Column('plans_updated', sa.Integer(), nullable=False),
    sa.Column('plans_removed', sa.Integer(), nullable=False),
    sa.Column('campaigns_found', sa.Integer(), nullable=False),
    sa.Column('changes_detected', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_stack', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('scraper_version', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_isp_id'), 'scrape_runs', ['isp_id'], unique=False)
    op.create_index(op.f('ix_scrape_runs_started_at'), 'scrape_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_scrape_runs_status'), 'scrape_runs', ['status'], unique=False)
    op.create_table('change_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.Enum('price_decrease', 'price_increase', 'plan_added', 'plan_removed', 'speed_change', 'bundle_added', 'bundle_removed', 'campaign_started', 'campaign_ended', 'fup_change', 'contract_change', name='changetype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='severitylevel'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diff_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_sent', sa.Boolean(), nullable=False),
    sa.Column('alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_channels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('scrape_run_id', sa.String(length=36), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_logs_alert_sent'), 'change_logs', ['alert_sent'], unique=False)
    op.create_index(op.f('ix_change_logs_change_type'), 'change_logs', ['change_type'], unique=False)
    op.create_index(op.f('ix_change_logs_detected_at'), 'change_logs', ['detected_at'], unique=False)
    op.create_index(op.f('ix_change_logs_isp_id'), 'change_logs', ['isp_id'], unique=False)
    op.create_index(op.f('ix_change_logs_plan_id'), 'change_logs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_change_logs_severity'), 'change_logs', ['severity'], unique=False)
    op.create_table('pricing_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('isp_id', sa.Integer(), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_quarterly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_annual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('download_mbps', sa.Integer(), nullable=False),
    sa.Column('upload_mbps', sa.Integer(), nullable=True),
    sa.Column('fup_gb', sa.Integer(), nullable=True),
    sa.Column('bundle_flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('scrape_run_id', sa.String(length=36), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isp_id'], ['isps.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_history_isp_id'), 'pricing_history', ['isp_id'], unique=False)
    op.create_index(op.f('ix_pricing_history_plan_id'), 'pricing_history', ['plan_id'], unique=False)
    op.create_index(op.f('ix_pricing_history_recorded_at'), 'pricing_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricing_history_recorded_at'), table_name='pricing_history')
    op.drop_index(op.f('ix_pricing_history_plan_id'), table_name='pricing_history')
    op.drop_index(op.f('ix_pricing_history_isp_id'), table_name='pricing_history')
    op.drop_table('pricing_history')
    op.drop_index(op.f('ix_change_logs_severity'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_plan_id'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_isp_id'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_detected_at'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_change_type'), table_name='change_logs')
    op.drop_index(op.f('ix_change_logs_alert_sent'), table_name='change_logs')
    op.drop_table('change_logs')
    op.drop_index(op.f('ix_scrape_runs_status'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_started_at'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_isp_id'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index(op.f('ix_plans_status'), table_name='plans')
    op.drop_index(op.f('ix_plans_price_monthly'), table_name='plans')
    op.drop_index(op.f('ix_plans_plan_type'), table_name='plans')
    op.drop_index(op.f('ix_plans_isp_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_download_mbps'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_campaigns_isp_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_is_active'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_isps_slug'), table_name='isps')
    op.drop_index(op.f('ix_isps_is_competitor'), table_name='isps')
    op.drop_table('isps')
    op.drop_table('intel_rules')
    # ### end Alembic commands ###
